name: Keep Render Service Alive

on:
  schedule:
    # Ejecuta cada 5 minutos (formato cron UTC)
    - cron: "*/5 * * * *"

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
        - name: Enviar ping
          run: |
            MAX_RETRIES=3
            RETRY_DELAY=10
            
            for i in $(seq 1 $MAX_RETRIES); do
                if curl -sSf -X GET "https://task-ninja-bot.onrender.com/health"; then
                echo "✅ Ping exitoso"
                exit 0
                else
                echo "❌ Fallo en el intento $i. Reintentando en $RETRY_DELAY segundos..."
                sleep $RETRY_DELAY
                fi
            done
            echo "🔥 Todos los intentos fallaron"
            exit 1